services:
  webhook:
    image: ghcr.io/always1ov/webhook:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      HOST: "0.0.0.0"
      PORT: "9000"
      HOT_RELOAD: "true"
      VERBOSE: "true"
      HOOKS_DIR: "/hooks"
      LANGUAGE: "zh-CN"
      WEBUI: "true"
      CUSTOM_HOOKS_FILE: "/data/custom-hooks.json"
      NOTIFY_CONFIG_FILE: "/data/notify.config.json"
    volumes:
      - ./hooks:/hooks
      - ./data:/data
